export const INITIALIZER_TOKENS = [
  'APP_INITIALIZER',
  'CACHE_INITIALIZER',
  'CIRCUIT_BREAKER_INITIALIZER',
  'COMPUTE_INITIALIZER',
  'COMPUTE_MODULE_OPTIONS',
  'DATABASE_INITIALIZER',
  'LIFECYCLE_INITIALIZER',
  'LOGGER_INITIALIZER',
  'REDIS_INITIALIZER',
  'GRAPHQL_INITIALIZER',
  'KAFKA_INITIALIZER',
  'NOTIFICATION_INITIALIZER'
] as const;
